apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres  # 서버(노드)에 실제 저장될 경로
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 3                  # 과거 3개까지만 보관
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          securityContext:
            runAsUser: 0          # ← initContainer만 root로 실행
            runAsGroup: 0
            allowPrivilegeEscalation: false
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /var/lib/postgresql/data/pgdata && \
              chown -R 999:999 /var/lib/postgresql/data && \
              chmod 700 /var/lib/postgresql/data && \
              chmod 700 /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "COMP_VALUE"
            - name: POSTGRES_USER
              value: "compvalue"
            - name: POSTGRES_PASSWORD
              value: "compvalue"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort  # 외부 접근 가능
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30032  # 노드 외부 접근 포트 (선택, 없으면 자동할당)
  selector:
    app: postgres