# frontend 기본 values 설정입니다.
# YAML 형식의 파일이며, 템플릿에 전달될 변수들을 정의합니다.

# 파드 복제본 수 설정 (ReplicaSet에 적용)
replicaCount: 1

# 컨테이너 이미지 설정
image:
  repository: ghcr.io/gnsgmlckdgk/comp-value-admin  # 사용할 이미지 저장소
  pullPolicy: Always  # 이미지 풀 정책 (이미지가 없을 때만 가져옴)
  tag: "latest"  # 이미지 태그 (기본값은 차트 appVersion)

# 프라이빗 레지스트리에서 이미지를 가져올 때 사용하는 시크릿 설정
imagePullSecrets: 
  - name: ghcr-secret

# 차트 이름을 오버라이드할 수 있는 옵션
nameOverride: ""
fullnameOverride: "comp-value-admin"

# 서비스 어카운트 설정
serviceAccount:
  create: true        # 새로운 서비스 어카운트 생성 여부
  automount: true     # API 토큰 자동 마운트 여부
  annotations: {}     # 서비스 어카운트에 붙일 어노테이션
  name: ""            # 사용할 서비스 어카운트 이름 (비워두면 자동 생성됨)

# 파드에 붙일 어노테이션
podAnnotations: {}

# 파드에 붙일 레이블
podLabels:
  app: comp-value-admin

# 파드 보안 컨텍스트 설정
podSecurityContext: {}
  # fsGroup: 2000

# 컨테이너 보안 컨텍스트 설정
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# 서비스 설정
service:
  type: NodePort   # 서비스 타입 (예: ClusterIP, NodePort, LoadBalancer 등)
  port: 80          # 서비스 포트
  nodePort: 30001
  targetPort: 80

# 인그레스 설정
ingress:
  enabled: false        # 인그레스 활성화 여부
  className: ""         # 인그레스 클래스 이름 (예: nginx)
  annotations: {}       # 인그레스에 붙일 어노테이션
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []               # TLS 설정 (예: 인증서, 비밀키 등)
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# 리소스 요청/제한 설정
resources: {}
  # 디폴트로는 설정하지 않음. 설정하려면 아래 주석을 해제하고 값 수정.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# 헬스체크 (liveness, readiness) 설정
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# 오토스케일링 설정
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# 추가 볼륨 정의
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# 추가 볼륨 마운트 정의
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# 노드 셀렉터 설정
nodeSelector: 
  kubernetes.io/hostname: wk1

# 톨러레이션 설정 (예: 특정 노드에만 스케줄링 허용)
tolerations: []

# 파드 간의 친화성 설정
affinity: {}
