apiVersion: apps/v1
kind: Deployment
metadata:
  name: comp-value-web
  labels:
    app: comp-value-web
spec:
  replicas: 1                              # 프론트는 1개부터 시작
  selector:
    matchLabels:
      app: comp-value-web
  template:
    metadata:
      labels:
        app: comp-value-web
    spec:
      containers:
        - name: comp-value-web
          image: ghcr.io/gnsgmlckdgk/comp-value-admin-v2:latest  # React build 포함된 nginx 이미지
          imagePullPolicy: Always                                 # latest는 Always 추천
          ports:
            - containerPort: 80                                   # 컨테이너 내부 Nginx 포트
          # (선택) 헬스체크 필요 시 주석 해제
          # readinessProbe:
          #   httpGet: { path: /, port: 80 }
          #   initialDelaySeconds: 3
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet: { path: /, port: 80 }
          #   initialDelaySeconds: 10
          #   periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: comp-value-web
  labels:
    app: comp-value-web
spec:
  type: NodePort
  selector:
    app: comp-value-web
  ports:
    - name: http
      nodePort: 30080                    # 서버 Nginx가 127.0.0.1:30080으로 프록시
      port: 80
      targetPort: 80