tunnel: compvalue-tunnel
credentials-file: /Users/hch/.cloudflared/cf2036cf-2c2b-4778-995a-0be517e20201.json

ingress:
  - hostname: compvalue.xyz
    service: http://localhost:80
  - service: http_status:404%